version: "3.7"
services:
  web:
    build: .
    restart: always
    depends_on:
      - backend
    ports:
      - "5000:5000"
  backend:
    build: ./api
    restart: always
    depends_on:
      - db
    ports:
      - "5001:5001"
  db:
    image: mongo:latest
    restart: always
    container_name: "db"
    volumes:
      - ~/mongo/data:/data/db
    ports:
      - "27017:27017"
