version: "3.8"
services:
  interface:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - api
    links:
      - api
  api:
    build: ./api
    ports:
      - 5000:5000
    depends_on:
      - mongo
    links:
      - mongo
  mongo:
    image: mongo:latest
    container_name: "mongo"
    ports:
      - 27017:27017
